import matplotlib.pyplot as plt

# Initialize lists to store cores and times
cores = []
times = []

# Read the times from the file generated by the SLURM job
with open('all_times.txt', 'r') as f:
    next(f)  # Skip the header
    for line in f:
        core, time = line.strip().split(',')
        cores.append(int(core))
        times.append(float(time))

# Plot cores vs time
plt.plot(cores, times, marker='o')
plt.xlabel('Number of Cores')
plt.ylabel('Time Taken (seconds)')
plt.title('Number of Cores vs Time Taken')
plt.grid(True)

# Save the plot as PNG
plt.savefig('core_vs_time.png')
